all:
  children:
    production:
      children:
        appservers:
          hosts:
            10.1.10.10:
              ansible_user: vagrant
        dbservers:
          hosts:
            10.1.20.10:
              ansible_user: vagrant
